package rainfall.main;

/**
 * Error that happens while parsing command-line arguments.
 */
final class ArgumentError extends Error {
  /**
   * Constructs an argument error that was generated by logic.
   *
   * @param message Message of the error.
   */
  ArgumentError(String message) {
    super(message);
  }

  /**
   * Constructs an argument error that was caused by another throwable.
   *
   * @param message Message of the error.
   * @param cause   Throwable that caused the error.
   */
  ArgumentError(String message, Throwable cause) {
    super(message, cause);
  }
}
